FROM downloads.unstructured.io/unstructured-io/unstructured:latest

WORKDIR /app

# dependency 
RUN pip install unstructured

# we'll mount the local directory to /app when running the container for now so no need to copy over files
# COPY . /app
